name: reviewdog

on:
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install dependencies
      run: |
        corepack enable && pnpm install
    - uses: reviewdog/action-setup@v1
    - name: megalodon eslint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pnpm --filter megalodon lint | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true
    - name: example/typescript eslint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pnpm --filter example lint | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true
    - name: example/browser eslint
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pnpm --filter browser lint | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true
