name: Test

on:
  push:
    branches:
      - master

    tags:

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          pnpm i
      - name: Build
        run: |
          pnpm --filter megalodon run build
      - name: Testing
        run: |
          pnpm --filter megalodon run test
      - name: Browser example
        run: |
          pnpm --filter browser run build
      - name: Typescript example
        run: |
          pnpm --filter example run build
