name: Test

on:
  push:
    branches:
      - master

    tags:

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        bun-version: ['latest']

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn workspace megalodon run build
      - name: Testing
        run: |
          yarn workspace megalodon run test
      - name: Browser example
        run: |
          yarn workspace browser run build
      - name: Typescript example
        run: |
          yarn workspace example run build
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Build (Bun)
        run: cd megalodon && bun run build:bun
      - name: Testing (Bun)
        run: bun run test
      - name: Browser example (Bun)
        run: cd ../example/browser && bun run build:bun
      - name: Typescript example (Bun)
        run: cd ../typescript && bun run build
