name: Test

on:
  push:
    branches:
      - master

    tags:

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          corepack enable && pnpm install
      - name: Build
        run: |
          pnpm -r run build
      - name: Testing
        run: |
          pnpm --filter megalodon run test

  example:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          corepack enable && pnpm install
      - name: Build library and examples
        run: |
          pnpm -r run build
      - name: Typescript example
        env:
          MASTODON_URL: https://fedibird.com
          PLEROMA_URL: https://pleroma.io
          FIREFISH_URL: https://cybre.club
          FRIENDICA_URL: https://squeet.me
        run: |
          node example/typescript/dist/mastodon/instance.js
          node example/typescript/dist/pleroma/instance.js
          node example/typescript/dist/firefish/instance.js
          node example/typescript/dist/friendica/instance.js
